name: {{project_name.snakeCase()}}
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.8
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  go_router: ^17.3.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
